### ISSUE TITLE
Property 'start' does not exist on type 'typeof RPC'.

### ISSUE THREAD

**Issue by jwulf** [xuezier/grpc-server-ts#1]
With this minimal server, I get an error:
```
import { Route, Service } from "grpc-server-ts";
import {db} from './db'
import { RpcRegistry, Settings } from 'grpc-server-ts';

const settings = {
  port: "50050",                     // listen port
  host: "localhost",                // listen host
  ca: "runtime/rpc/ca.crt",         // ca file path
  cert: "runtime/rpc/server.crt",   // cert file path
  key: "runtime/rpc/server.key"     // key file path
}

@Service('proto/users.proto')
export class UserService {
  @Route
  public async Get(user_id) {
    return await new Promise(res => db.get(user_id, (err, user) => res(user)))
  }

  @Route
  public async List() {
    return await new Promise(res => db.list((err, user) => res(user)))
  }
}

@Settings(settings)
class RPC extends RpcRegistry { }
RPC.start();
```
When I try to compile it:
```
ts-node src/server/index.ts
```
I get this (same error in VSCode via intellisense):
```
/usr/local/opt/nvm/versions/node/v10.9.0/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/server/index.ts(28,5): error TS2339: Property 'start' does not exist on type 'typeof RPC'.
```

**Comment by jwulf** [comment]
Side-note: the npm package has no type definitions?

**Comment by xuezier** [comment]
what version of ts-node are you used?
can you try ts-node: v4.x again?

**Comment by xuezier** [comment]
> Side-note: the npm package has no type definitions?

**[discard]**

Oh, I was so busy that forgot to finish it😂. so a long time passed......
I will complete the .d.ts in this month.

**Comment by xuezier** [comment]
> Side-note: the npm package has no type definitions?

Ok, it seems that i was set `declaration: false` in tsconfig.json.
i was publish a new package to npm.
you can reinstall the new version of package to resolve this problem.

thank you !!!

**Comment by xuezier** [comment]
> Side-note: the npm package has no type definitions?

If there are no other questions，I will close this issue.

**Comment by jwulf** [comment]
With the new package I get a different error:
<img width="661" alt="screen shot 2018-11-23 at 2 01 32 pm" src="https://user-images.githubusercontent.com/406975/48928214-665e8180-ef28-11e8-9df1-134a7d6aba5d.png">

**Comment by jwulf** [comment]
The code is like this:

```typescript
@Service('proto/users.proto')
export class UsersService {
  @Route
  public async get(user_id) {
    console.log(`Received get request for ${user_id}`)
    return new Promise(res => db.get(user_id, (err, user) => res({user: [user]})))
  }
}
```

**Comment by jwulf** [comment]
I can get the error to disappear if I do this in `decorator/Route.ts`:

```typescript
export function Route(target: any, key: string, { value: route }: { value?: any }) {
```

The Method decorator signature in the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/decorators.html) has such an `any` signature for the target.

The optional and `any` type on `value` I added to suppress a further error that appeared after relaxing the type of `target`.
