### ISSUE TITLE
Server does not respond to client requests

### ISSUE THREAD

**Issue by jwulf** [xuezier/grpc-server-ts#6]
I have a basic demo project here: https://github.com/jwulf/grpc-demo

Take 1 uses a straight-up server, and works. To run it, cd into the `Take1` directory, run `npm i`, then run `npm run server` in one terminal and `npm run client` in another terminal.

Outcome: The client makes gRPC calls to the server and gets data back.

<img width="1132" alt="screen shot 2018-11-23 at 2 54 29 pm" src="https://user-images.githubusercontent.com/406975/48928949-b8ef6c00-ef2f-11e8-9b4b-b174427aef0d.png">

Take 2 uses grpc-server-ts. To run it, cd into the `Take2` directory, run `npm i`, then run `npm run server` in one terminal and `npm run client` in another terminal.

Note: You need to apply the run-unsecured patch, and either apply the remove-deprecation-notice patch or change the case of the route methods.

Outcome: The server does not respond.

<img width="1136" alt="screen shot 2018-11-23 at 2 55 04 pm" src="https://user-images.githubusercontent.com/406975/48928952-c73d8800-ef2f-11e8-9911-d0055a83ea11.png">

**Comment by xuezier** [comment]
It's because I only implemented transfer stream data.
I have improved it. please reinstall the new version of package.

thanks.

**Comment by jwulf** [comment]
Looks like this issue is fixed by this patch, however it introduces a new issue - opened as #7

**Comment by jwulf** [comment]
Working.
